FROM node:12.16.1-alpine3.11 AS build
WORKDIR /app
ARG REACT_API_APP

COPY . .
RUN yarn install

RUN REACT_API_APP=${REACT_API_APP} yarn build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]