version: "3.4"
services:
    client:
        restart: always
        build: 
            context: client
            dockerfile: Dockerfile.develop
            args: 
                - REACT_API_APP=http://localhost:5000
        ports:
            - 3000:80
    api:
        restart: always
        build:
            context: api
            dockerfile: Dockerfile.develop
        env_file: 
            - api/.env
        environment:
            - NODE_ENV=production
            - PORT=5000
        ports: 
            - 5000:5000
        depends_on: 
            - db
    db:
        container_name: quality_db
        image: postgres:10.12-alpine
        restart: always
        ports: 
            - 5433:5432
        env_file: 
            - api/.env
        environment: 
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes: 
            - /custom/mount:/var/lib/postgresql/data