export enum Profile {
	PROFILE = "PROFILE",
	UX_PROFILE = "UX_PROFILE",
	UI_PROFILE = "UI_PROFILE",
	BASE_PROFILE = "BASE_PROFILE",
	VERBAL_PROFILE = "VERBAL_PROFILE",
	FAULTS_INJECTION_PROFILE = "FAULTS_INJECTION_PROFILE",
}
