name: Deploy backend to heroku
on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
jobs:
  build_back_end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "quality-assessment-back-end"
          heroku_email: "kendis_it@hotmail.com"
          usedocker: true
          appdir: "api"